// 1. RÉFÉRENTIELS
const CAT = ["Catalogue", "Nouveauté", "As d'Or", "Perso"];
const TYPE = ["Tout Public", "Initié", "Expert", "Enfant", "Ambiance", "Duel"];

// 2. DATA BRUTE (Format: ID, Titre, CatIndex, TypeIndex, Editeur, Auteur, Stand, Joueurs, Temps, Description)
const rawGames = [
  // --- AS D'OR 2025 & INCONTOURNABLES ---
  [1, "Flip 7", 2, 4, "Catch Up Games", "Eric S. Burgess", "10.01", "3-8", "20 min", "Stop-ou-encore addictif. Posez des cartes pour le score, mais si une valeur se répète, vous perdez tout."],
  [2, "Rebirth", 1, 1, "Lucky Duck Games", "Reiner Knizia", "05.01", "2-4", "45 min", "Pose de tuiles stratégique. Reconstruisez l'Écosse en reliant châteaux et territoires pour des majorités."],
  [3, "Toy Battle", 1, 5, "Repos Production", "Mori & Zucchini", "09.01", "2", "20 min", "Jeu de plis pour 2 joueurs sans obligation de couleur. Créez votre armée de jouets pour dominer l'adversaire."],
  [4, "Archeo", 1, 3, "Gigamic", "Yohan Servais", "20.02", "1-5", "20 min", "Exploration coopérative. Fouillez les cartes lieux et gérez vos outils pour trouver des trésors avant la fin du temps."],
  [5, "L'Île des Mookies", 1, 3, "Le Scorpion Masqué", "M. & W. Fort", "14.06", "2-5", "15 min", "Coopératif et mémoire. Déplacez les Mookies pour aligner les objets et les nourrir selon leurs envies changeantes."],
  [6, "La Valse des Fantômes", 1, 3, "Schmidt Spiele", "Steffen Bogen", "19.06", "1-4", "20 min", "Adresse et mémoire. Déplacez des fantômes magnétiques à travers des murs invisibles pour rejoindre vos objets."],
  [7, "First Rat", 0, 1, "Pegasus / Tribuo", "Ausiello & Gigli", "13.01", "1-5", "60 min", "Course stratégique. Gérez les ressources de vos rats pour construire une fusée et atteindre la Lune de Fromage."],
  [8, "Take Time", 1, 1, "Libellud", "Loïc Lamy", "18.03", "2-4", "30 min", "Jeu d'observation en temps limité. Trouvez les meilleures combinaisons sur le plateau avant que le sablier ne s'écoule."],
  [9, "Zenith", 1, 1, "Playpunk", "Bauza & Maublanc", "16.01", "2-4", "30 min", "Contrôle de territoire en 3D. Utilisez vos pièces pour grimper le plus haut possible et écraser les majorités adverses."],
  [10, "Arcs", 2, 2, "Leder / Matagot", "Cole Wehrle", "24.03", "2-4", "120 min", "Space-opera épique. Un jeu de plis guide vos actions (guerre, recherche, construction) dans une campagne asymétrique."],
  [11, "Civolution", 2, 2, "Deep Print / Matagot", "Stefan Feld", "24.03", "1-4", "180 min", "Civilisation expert. Un immense bac à sable de gestion de dés pour faire évoluer votre peuple sur des millénaires."],
  [12, "Fourmis", 1, 2, "Intrafin Games", "Yoann Levet", "14.08", "2-4", "90 min", "4X à l'échelle micro. Gérez votre colonie, explorez le jardin, produisez des phéromones et combattez pour survivre."],

  // --- CATALOGUE & HITS RECENTS ---
  [301, "Harmonies", 2, 0, "Libellud", "Johan Benvenuto", "18.03", "1-4", "30 min", "Draft et motifs 3D. Créez des paysages verticaux pour accueillir des animaux selon leurs besoins d'habitat."],
  [302, "The White Castle", 0, 2, "Devir / Iello", "Santos & Cendrero", "12.01", "1-4", "80 min", "Gestion de dés et combos. Optimisez chaque action dans un château japonais pour marquer un maximum en seulement 3 tours."],
  [303, "Nekojima", 0, 0, "Unfriendly Games", "Carmona & Nguyen", "18.06", "1-5", "20 min", "Adresse sous tension. Empilez des poteaux électriques reliés par des fils et placez des chats sans tout faire tomber."],
  [304, "Faraway", 0, 1, "Catch Up Games", "Goupy & Lebrat", "10.01", "2-6", "25 min", "Tableau building malin. Posez des cartes aventuriers, mais attention : le scoring se calcule à l'envers, de la fin au début !"],
  [305, "Evenfall", 0, 2, "Matagot", "Stefano Di Silvio", "24.03", "1-4", "90 min", "Engine building magique. Gérez votre mana et vos rituels pour contrôler des lieux de pouvoir dans un univers sombre."],

  // --- AJOUTS MANQUANTS (AS D'OR & BUZZ) ---
  [401, "Odin", 2, 0, "Helvetiq", "Goh, Kim & Hwang", "16.01", "2-6", "15 min", "Jeu de défausse minimaliste. Posez une combinaison plus forte que la précédente pour vider votre main le plus vite possible."],
  [402, "Captain Flip", 2, 0, "Playpunk", "Mori & Conzadori", "16.01", "2-5", "20 min", "Tuiles et prise de risque. Tirez une tuile : gardez-la ou retournez-la pour son effet, au risque de couler votre navire."],
  [403, "For a Crown", 2, 0, "Repos Production", "Maxime Rambourg", "09.01", "2-4", "30 min", "Plis et déduction. Gagnez des plis pour placer des jetons et devinez l'identité du prétendant au trône de vos adversaires."],
  [404, "Kutná Hora", 2, 2, "Iello", "Bystroň, Jarosch & Čáslava", "12.01", "2-4", "90 min", "Eurogame économique. Bâtissez une cité médiévale avec un système d'offre et de demande dynamique qui impacte tous les prix."],
  [405, "Sankoré", 2, 2, "Super Meeple", "Lopiano & Fernandez", "05.05", "1-4", "150 min", "Gestion experte. Dirigez une prestigieuse université africaine du 14e siècle en gérant 4 disciplines académiques."],
  [406, "Opération Noisettes", 2, 3, "Auzou", "J. & E. Soleil", "11.01", "1-4", "15 min", "Coopératif spatial. Aidez l'écureuil à mémoriser et traverser la forêt pour cacher ses noisettes avant l'hiver."],
  [407, "Les Éclairtout", 2, 3, "Loki", "Hach & Silva", "12.01", "2-4", "15 min", "Cherche et trouve tactique. Éclairez les bonnes zones du plateau pour trouver des trésors cachés dans l'ombre."],
  [408, "Mimose & Sam", 2, 3, "Locomuse", "T. Dagenais-Lespérance", "Espace Enfant", "2-4", "20 min", "Enquête évolutive. Un jeu de cartes où les enfants incarnent des chats-détectives avec des scénarios à résoudre."],
  [409, "Daybreak", 2, 2, "Intrafin / CMYK", "Matt Leacock", "14.08", "1-4", "90 min", "Coopératif écologique. Par l'auteur de Pandemic : gérez des technologies vertes pour décarboner la planète avant l'emballement."],
  [410, "King of Tokyo: Duel", 1, 5, "Iello", "Richard Garfield", "12.01", "2", "20 min", "Affrontement de monstres. La version 2 joueurs du classique : tir à la corde sur des pistes de pouvoir et lancers de dés."],
  [411, "SETI", 1, 2, "Iello / CGE", "Tomáš Holek", "12.01", "1-4", "120 min", "Eurogame scientifique. Scannez le ciel et lancez des sondes pour rechercher des traces de vie extraterrestre."],
  [412, "Panda Spin", 1, 0, "Matagot", "Yoann Levet", "24.03", "2-5", "20 min", "Jeu de défausse malin. Si vous ne pouvez pas jouer, pivotez vos cartes pour changer leur valeur et revenir plus fort."],
  [413, "Kelp", 1, 5, "Matagot / Wonderbow", "Carl Robinson", "24.03", "2", "45 min", "Duel asymétrique. Le Requin (dés et déplacements cachés) traque le Poulpe (deck-building et bluff) dans la forêt de varech."],
  [414, "Gatsby", 1, 0, "Catch Up Games", "Bleau & Cravotta", "10.01", "2-5", "45 min", "Collection et corruption. Organisez les meilleures fêtes des années 20 en gérant vos invités et vos ressources."],
  [415, "All-Star Draft", 1, 0, "Palladis Games", "Marco Pranzo", "05.08", "2-6", "30 min", "Draft de sport. Composez la meilleure équipe de hockey et gérez vos joueurs entre la patinoire et les tribunes."],
  [416, "Ironwood", 1, 5, "Super Meeple", "L.D. Gáspár", "05.05", "1-2", "60 min", "Duel asymétrique intense. Le peuple du Bois (furtif) affronte le peuple du Fer (destructeur) pour le contrôle des totems."],
  [417, "Agent Avenue", 1, 5, "Iello", "Indie Boards & Cards", "12.01", "2", "20 min", "Bluff et partage. Mécanique du 'je coupe, tu choisis' pour récupérer des agents secrets tout en évitant les assassins."],

  // --- LISTE GENERALE ---
  [101, "Patata!", 1, 4, "23 zéro", "Julien Sentis", "10.12", "2-99", "30 min", "Party game explosif. Une patate chaude revisitée où l'on doit valider des défis avant de passer le relais."],
  [102, "Save Us All", 1, 1, "Abym games", "Nicolas Robert", "03.04", "4-8", "120 min", "Coopératif expert. Protégez l'humanité en gérant des ressources et des crises dans un univers tendu."],
  [103, "Magna Roma", 0, 2, "Archona / Blackrock", "Stan Kordonskiy", "16.01", "1-4", "90 min", "Pose de tuiles. Construisez la plus belle cité romaine, les bonus se déclenchent selon les connexions adjacentes."],
  [104, "Philarmonix", 1, 2, "Archona Games", "Kostas Karamanis", "16.01", "1-4", "150 min", "Gestion spatiale. Gérez un orchestre symphonique intergalactique, recrutez des musiciens et jouez des concerts."],
  [105, "The Royal Society", 1, 2, "Atalia", "Lauge Luchau", "17.03", "1-4", "120 min", "Enchères et collection. Rivalisez de prestige au sein de la société scientifique pour financer vos expéditions."],
  [106, "Pas touche", 1, 3, "Atalia", "Inka & Markus Brand", "17.03", "2-6", "15 min", "Observation rapide. Repérez l'objet interdit selon les cartes et soyez le premier à ne pas le toucher (ou l'attraper)."],
  [107, "Formula 5", 1, 0, "Atalia", "Lauge Luchau", "17.03", "2-5", "15 min", "Course de dés. Gérez votre vitesse et votre prise de risque pour franchir la ligne d'arrivée sans sortir de piste."],
  [108, "7 Leagues", 1, 0, "ATM Gaming", "Bastien Guégan", "07.07", "2-6", "20 min", "Connexion de route. Posez vos bottes de 7 lieues pour créer le chemin le plus optimisé à travers le royaume."],
  [109, "Paire de Choc", 1, 4, "Bandjo", "Bandjo Studio", "11.01", "2-15", "30 min", "Ambiance coopérative. Trouvez des paires d'images correspondantes avec votre partenaire sans parler."],
  [110, "To me! ...or not?", 1, 4, "Bankiiiz", "Romaric Galonnier", "14.01", "3-6", "20 min", "Communication limitée. Demandez des objets aux autres joueurs, mais vos envies sont secrètes et changent."],
  [111, "Trait Cool", 1, 0, "Bankiiiz", "Romain Caterdjian", "14.01", "2-8", "30 min", "Roll & Write coopératif. Reliez des numéros sur votre feuille en suivant les contraintes dictées par les dés communs."],
  [112, "Vroom", 1, 0, "Big moustache", "Frédéric Moyersoen", "08.03", "3-6", "15 min", "Course d'obstacles. Un jeu de cartes rapide où il faut doubler les adversaires en jouant les bonnes vitesses."],
  [113, "Limit", 1, 2, "Blackrock", "Alexandre Poyé", "16.01", "1-6", "150 min", "Stratégie économique. Gérez les ressources et les limites de votre entreprise dans un marché fluctuant."],
  [114, "Mozaik", 0, 0, "Blam!", "Julien Prothière", "13.02", "1-4", "30 min", "Dessin tactique. Cochez des cases sur votre mosaïque selon les cartes communes pour créer les meilleurs motifs."],
  [115, "Chouineurs", 1, 4, "Blam!", "Ludovic Maublanc", "13.02", "3-5", "20 min", "Jeu de plis de mauvaise foi. Gagnez des plis, mais attention aux malus si vous râlez ou ne respectez pas les contraintes."],
  [116, "Derniers droides", 1, 1, "Blue cocker", "Alain Rivollet", "16.01", "1-4", "40 min", "Programmation et survie. Incarnez des droïdes cherchant à s'échapper d'un vaisseau en panne en gérant votre batterie."],
  [117, "Ice Split", 1, 0, "Blue orange", "Théo Rivière", "11.02", "2-4", "15 min", "Bluff et collection. Partagez le butin (poissons) avec les autres, mais gardez les meilleures parts pour vous."],
  [118, "A_way", 1, 0, "Blue orange", "Blue Orange Team", "11.02", "2-4", "30 min", "Pose de tuiles labyrinthique. Créez des chemins pour connecter vos points de départ et d'arrivée avant les autres."],
  [119, "Got five", 1, 0, "Blue orange", "Christian Giove", "11.02", "2-4", "15 min", "Déduction logique. Trouvez le code caché ou la combinaison de l'adversaire en proposant des séquences de 5."],
  [120, "Secrets de Warden", 1, 1, "Bombyx", "Matthew Dunstan", "30.02", "1-4", "30 min", "Enquête narrative. Observez les cartes et combinez les indices pour résoudre le mystère du manoir Warden."],
  [121, "Knarr : Skali", 1, 1, "Bombyx", "Thomas Dupont", "30.02", "2-4", "30 min", "Extension de Knarr. Ajoute de nouvelles cartes et mécaniques pour enrichir vos raids et votre commerce viking."],
  [122, "Map Masters", 1, 0, "Captain games", "Ian S. Bach", "10.01", "1-5", "45 min", "Course au trésor. Planifiez simultanément vos déplacements sur la carte pour récupérer le butin avant les autres."],
  [123, "Tea and Rum", 1, 2, "Captain games", "Phil Northcott", "10.01", "2-4", "120 min", "Commerce maritime. Naviguez entre les ports, achetez du thé et du rhum, et optimisez votre cale pour la revente."],
  [124, "Heredity: Lexington", 1, 2, "Darucat", "Cance & Kobel", "10.12", "1-4", "150 min", "Aventure narrative coopérative. Une campagne post-apocalyptique où vos choix impactent l'histoire et votre lignée."],
  [125, "Chateau combo", 1, 1, "Catch Up games", "Grard & Roussel", "10.01", "2-5", "30 min", "Tableau building. Achetez des cartes personnages pour remplir votre grille et déclencher des synergies de points."],
  [126, "Red Notice", 1, 4, "Catch Up games", "B. Laurent & G. De Cottreau", "10.01", "2-8", "30 min", "Déduction sociale. Trouvez qui sont les voleurs parmi les joueurs tout en collectant des œuvres d'art."],
  [127, "Matchy Matchy", 1, 4, "Cocktail games", "Favre-Godal & Lebrat", "09.16", "3-8", "30 min", "Jeu d'ambiance en équipe. Trouvez un lien secret entre deux cartes images pour que votre partenaire le devine."],
  [128, "Kumata", 1, 0, "Cosmoludo", "Pierre Canuel", "09.08", "2-4", "20 min", "Stratégie abstraite. Déplacez vos ours polaires pour bloquer les mouvements adverses et contrôler la banquise."],
  [129, "Alchimix", 1, 1, "CTRL Zèbre", "Alexis Aspecada", "05.02", "2-5", "20 min", "Combinaison de cartes. Mélangez des ingrédients primaires pour créer des potions et marquer des points."],
  [130, "Quintessence", 1, 1, "CTRL Zèbre", "Fabrice Chazal", "05.02", "2-4", "45 min", "Contrôle de territoire. Utilisez les 5 éléments pour influencer les régions du plateau et dominer vos rivaux."],
  [131, "Charuma", 1, 0, "Darucat", "Takashi Saito", "10.12", "2-5", "45 min", "Plis et paris. Misez sur le nombre de plis que vous allez faire et utilisez des amulettes pour manipuler le jeu."],
  [132, "Battle of Hoth", 1, 0, "Days of Wonders", "Borg & Martinot", "09.01", "2-4", "30 min", "Wargame léger. Revivez la bataille emblématique de Star Wars : l'Empire attaque la base Echo, les Rebelles résistent."],
  [133, "Grizzy & Lemmings", 1, 3, "Débacle jeux", "Débacle Team", "09.01", "1-4", "15 min", "Coopératif fun. Utilisez les dés pour aider Grizzy à repousser les Lemmings qui envahissent la maison."],
  [134, "Daydream", 1, 0, "Disto studio", "Perone & Turpin", "31.01", "1-5", "30 min", "Loto onirique. Cochez des cases sur votre feuille de rêve en suivant les motifs révélés par les cartes."],
  [135, "Ding", 1, 0, "Don't panic", "Alexandre Droit", "07.01", "2-7", "10 min", "Défausse rapide. Un jeu de réflexe où il faut se débarrasser de ses cartes en réagissant au son 'Ding'."],
  [136, "Terres de destinées", 1, 1, "Don't panic", "Olivier Flament", "07.01", "2-6", "30 min", "Négociation et conquête. Étendez votre royaume, mais attention aux alliances fragiles et aux trahisons."],
  [137, "Styx", 1, 2, "Don't panic", "Pierre Lahmi", "07.01", "2-6", "45 min", "Enchères mythologiques. Payez Charon pour traverser le fleuve des Enfers, mais gérez bien vos âmes."],
  [138, "Goutons voir!", 1, 4, "Don't panic", "Christophe Lauras", "07.01", "2-5", "20 min", "Jeu sensoriel. Goûtez des aliments (réels ou simulés) et devinez les ingrédients ou les saveurs."],
  [139, "Mon 1er Deck building", 1, 3, "Don't panic", "F. Chazal & A. Poyé", "07.01", "2-5", "15 min", "Initiation ludique. Apprenez les mécaniques d'achat de cartes et de construction de paquet dans un univers enfantin."],
  [140, "Fruit Cocktail", 1, 0, "Don't panic", "Don't Panic Team", "07.01", "2-4", "10 min", "Collection de sets. Récupérez les meilleurs fruits pour composer le cocktail le plus juteux (points)."],
  [141, "Spyworld", 1, 0, "Don't panic", "Don't Panic Team", "07.01", "2-4", "30 min", "Flip & Write d'espionnage. Remplissez vos missions secrètes en cochant des cases selon les cartes révélées."],
  [142, "Dozito", 1, 0, "Double combo", "Wolfgang Kramer", "11.04", "2-5", "20 min", "Placement stratégique. Posez des tuiles colorées pour créer des zones et marquer des points selon les majorités."],
  [143, "Crabes vs Poulpes", 1, 5, "La boîte de jeux", "Théo Rivière", "08.01", "2", "10 min", "Duel asymétrique rapide. L'un joue les crabes, l'autre les poulpes, chacun avec ses conditions de victoire."],
  [144, "1ers Contacts", 1, 2, "Explor8", "Damaso Rita", "16.01", "2-5", "60 min", "Déduction et communication. Les extraterrestres tentent de se faire comprendre des humains par des associations d'idées."],
  [145, "Bean to bar", 1, 2, "Fentasy games", "Geri Gallas", "03.05", "2-4", "180 min", "Gestion économique. De la fève à la tablette : gérez toute la chaîne de production d'une fabrique de chocolat."],
  [146, "Animal Rescue Team", 1, 0, "Fentasy games", "Matt Leacock", "03.05", "1-4", "60 min", "Coopératif tactique. Déplacez votre équipe pour soigner et sauver des animaux en danger à travers le monde."],
  [147, "Bellevue", 1, 0, "Gigamic", "Zach Hoekstra", "20.02", "2-5", "20 min", "Construction de ville. Draft et placement pour créer le plus beau panorama urbain et satisfaire les habitants."],
  [148, "Au Pif", 1, 4, "Gigamic", "Johnson & Langsworthy", "20.02", "1-8", "18 min", "Quiz d'estimation. Devinez des quantités absurdes (ex: nombre de poils sur un chat), le plus proche l'emporte."],
  [149, "Pirate King", 1, 0, "Gigamic", "Frankie Bu", "20.02", "2-5", "15 min", "Programmation simultanée. Choisissez secrètement votre action (piller, naviguer, attaquer) et révélez tout en même temps."],
  [150, "Ratak", 1, 4, "Gigamic", "Valentin Daubresse", "20.02", "2-6", "15 min", "Jeu de défausse rapide. Débarrassez-vous de vos cartes rats en piégeant les autres avec des effets spéciaux."],
  [151, "Micro Hero Hercule", 1, 1, "Gigamic", "Léandre Proust", "20.02", "1-2", "20 min", "Aventure minimaliste. Un jeu de poche où vous vivez les 12 travaux d'Hercule avec quelques cartes et des dés."],
  [152, "Misfit Heroes", 1, 1, "Gigamic", "Phil Walker-Harding", "20.02", "2-4", "45 min", "Deck-building fun. Créez des héros improbables (ex: Ninja-Robot) et faites-les combattre pour la gloire."],
  [153, "Pigeon explosion", 1, 0, "Gigamic", "Roberto Pellei", "20.02", "2-5", "30 min", "Ambiance chaotique. Gérez une invasion de pigeons en ville, provoquez des réactions en chaîne pour nettoyer la zone."],
  [154, "Medievallons", 1, 0, "Gigamic", "Coen Balkestein", "20.02", "2-5", "40 min", "Draft et collection. Recrutez des villageois médiévaux pour former les meilleures guildes et marquer des points."],
  [155, "La triplette", 1, 0, "Gigamic", "Alice & C. Cardin", "20.02", "2-4", "45 min", "Pétanque tactique sur table. Utilisez des dés et des cartes pour placer vos boules au plus près du cochonnet."],
  [156, "Bloody Grove", 1, 5, "Grrre Games", "Jérémy Belzons", "10.03", "2", "30 min", "Bluff et déduction. Un duel où il faut identifier les vampires adverses tout en protégeant les siens."],
  [157, "Trök", 1, 1, "Grrre Games", "S. Laget & B. Cathala", "10.03", "2-4", "40 min", "Négociation et collection. Échangez des ressources sur un marché dynamique pour compléter vos commandes."],
  [158, "Forest leader", 1, 0, "Haumea Games", "T. Carlier & E. Bede", "07.03", "3-6", "30 min", "Semi-coopératif. Gérez l'équilibre de la forêt ensemble, mais tentez d'être celui qui tire le plus de profit."],
  [159, "Wrath of Fire Mtn", 0, 1, "Iello", "Kevin Lanzing", "12.01", "2-4", "45 min", "Gestion de risque. Placez vos meeples pour récolter des gemmes, mais attention aux éruptions du volcan !"],
  [160, "Plante Bataille", 1, 0, "Iello", "Yukihito Morikawa", "12.01", "3-6", "15 min", "Bataille revisitée. Chaque joueur a une plante avec une force variable, choisissez intelligemment vos combats."],
  [161, "1 QUILLE !", 1, 0, "Iello", "Susumu Kawasaki", "12.01", "2-5", "20 min", "Adresse et dextérité. Tentez de faire tomber la quille rouge sans toucher les autres avec un système de pichenette."],
  [162, "Railroad Tiles", 1, 0, "Iello", "Hjalmar Hach", "12.01", "2-5", "30 min", "Connexion de tuiles. Créez le réseau ferré le plus efficace pour relier les gares et transporter des marchandises."],
  [163, "Freigard", 1, 5, "inPatience", "Shadi Torbey", "12.05", "1", "15 min", "Solo tactique. Un jeu de l'univers Oniverse où vous devez défendre une forteresse contre des vagues d'ennemis."],
  [164, "Mayor of Chicago", 1, 5, "inPatience", "Xavier Georges", "12.05", "1", "30 min", "Solo de gestion. Incarnez le maire, gérez la popularité, le budget et la criminalité pour vous faire réélire."],
  [165, "Echoes of time", 1, 2, "Intrafin", "S. Luciani & R. Pellei", "14.08", "2-4", "60 min", "Voyage temporel. Modifiez le passé pour influencer le futur et récupérer des artefacts historiques."],
  [166, "Light Speed Arena", 1, 4, "Intrafin", "James Ernest", "14.08", "1-4", "5 min", "Combat spatial temps réel. Posez vos cartes de tir le plus vite possible, puis on résout les lasers avec une ficelle."],
  [167, "Aquaria", 1, 2, "Intrafin", "Tomáš Holek", "14.08", "1-4", "60 min", "Gestion de main. Développez un écosystème sous-marin en jouant des cartes pour leurs effets ou comme ressources."],
  [168, "Dame Nature", 1, 0, "Jeux opla", "J. Prothière & D. Boniffacy", "13.08", "3-6", "15 min", "Jeu de connaissances. Pariez sur les caractéristiques des animaux et plantes pour montrer votre savoir naturaliste."],
  [169, "Pollen", 1, 5, "Jeux opla", "Florent Toscano", "13.08", "2", "15 min", "Duel de majorité. Attirez les insectes pollinisateurs sur vos fleurs pour remporter les tuiles jardin."],
  [170, "Le petit théatre", 1, 0, "Kodama", "Guidotti, German & Derouetteau", "03.06", "3-8", "30 min", "Narration et imagination. Créez des histoires ensemble en utilisant les éléments de décor du théâtre."],
  [171, "Miams", 1, 0, "KYF Editions", "Jules Messaud", "08.01", "1-5", "30 min", "Collection et prise de risque. Récupérez les meilleurs plats du buffet sans faire d'indigestion (dépasser 13)."],
  [172, "Grace", 1, 0, "La Rose noire", "Antoine Sauliere", "16.01", "2", "30 min", "Duel de cartes esthétique. Gérez votre main pour créer les plus belles chorégraphies et impressionner le public."],
  [173, "Ghost manor", 1, 3, "Laboludic", "Romaric Galonnier", "16.01", "2-4", "15 min", "Jeu de rapidité. Observez le manoir et soyez le premier à trouver où se cache le fantôme selon les indices."],
  [174, "Codex: Abbaye", 1, 2, "Le lion vert", "Fabien Clavel", "05.09", "1-99", "240 min", "Livre-jeu d'enquête géant. Explorez une abbaye médiévale, résolvez des énigmes et percez le secret des moines."],
  [175, "Gévaudan", 1, 2, "Le lion vert", "Aurélien Devaux", "05.09", "1-4", "30 min", "Déduction historique. Enquêtez sur la Bête du Gévaudan, éliminez les suspects et trouvez la vérité."],
  [176, "A wild Venture", 1, 0, "Lucky Duck", "Iain Everett", "05.01", "1-2", "60 min", "Aventure solo/duo. Explorez des terres sauvages, combattez des monstres et améliorez votre équipement."],
  [177, "Borealis", 1, 0, "Lucky Duck", "Dariusz Mindur", "05.01", "2-4", "45 min", "Draft et pyramide. Construisez un arbre de compétences et collectez des cristaux pour illuminer la nuit polaire."],
  [178, "Trinket trove", 1, 0, "Lucky Duck", "Rocco Privetera", "05.01", "2-6", "30 min", "Draft rapide. Passez les cartes et choisissez les meilleurs bibelots pour remplir vos étagères de collection."],
  [179, "Maki San", 1, 5, "Ludically", "M. Iaciancio & M. Lagroy", "07.04", "2", "15 min", "Déduction gourmande. Devinez la commande de sushis secrète de l'adversaire en posant des questions logiques."],
  [180, "Moustache", 1, 0, "Lumberjack", "Antonin Boccara", "08.01", "3-6", "20 min", "Jeu de plis original. La valeur des cartes dépend de la longueur de la moustache des personnages !"],
  [181, "Alice", 1, 0, "Lumberjack", "C. Alcouffe & L. Maublanc", "08.01", "2-6", "30 min", "Flip & Write féerique. Retournez des cartes et cochez votre feuille pour revivre les aventures d'Alice au Pays des Merveilles."],
  [182, "Faust Vs Mephisto", 1, 5, "Mandoo games", "Geonil", "18.07", "2", "25 min", "Duel psychologique. Incarnez le bien ou le mal et tentez de corrompre ou sauver l'âme de Faust."],
  [183, "Trucs en stock", 1, 4, "Matagot", "Peter C. Hayward", "24.03", "2-10", "20 min", "Party game de bluff. Cachez des objets bizarres dans votre 'entrepôt' et essayez de piéger les autres."],
  [184, "Bomb5", 1, 0, "Matagot", "Fabrice Puleo", "24.03", "2-5", "15 min", "Jeu d'ambiance. Posez des tuiles pour créer des chemins, mais évitez les bombes cachées sous peine d'élimination."],
  [185, "Goat simulator", 1, 4, "MOOD Publishing", "MOOD Team", "08.11", "3-6", "20 min", "Chaos total. Comme le jeu vidéo : faites n'importe quoi, détruisez le décor et marquez des points en étant une chèvre."],
  [186, "Yami", 1, 1, "Musoka studio", "Ohba, Perone, Suzuki & Tezuka", "16.05", "2-4", "30 min", "Coopératif asymétrique. Un joueur incarne l'Ombre, les autres des Héros qui doivent collaborer pour la vaincre."],
  [187, "All in : predictions", 1, 0, "Next move", "Phil Walker-Harding", "09.01", "2-5", "25 min", "Paris et bluff. Estimez combien de plis ou de défis les joueurs vont réussir et misez vos jetons."],
  [188, "Mini rogue : Conseil", 1, 1, "Nuts Publishing", "Di Stefano", "06.13", "1-2", "30 min", "Extension Dungeon Crawler. Ajoute de nouveaux personnages, salles et boss à l'excellent jeu solo/duo minimaliste."],
  [189, "Visions", 1, 0, "Olémains games", "B. Cathala & F. Sirieix", "08.09", "2-5", "30 min", "Observation et rapidité. Repérez des motifs dans les visions communes avant les autres médiums."],
  [190, "Pépite", 1, 4, "Openworld", "Amaury Montmoreau", "22.03", "3-6", "20 min", "Bluff et prise de risque. Incarnez des chercheurs d'or, mentez sur vos trouvailles pour voler les autres sans se faire prendre."],
  [191, "Etonak vanguard", 1, 2, "Ora games", "Thomas Sing", "04.08", "1-2", "60 min", "Affrontement tactique. Un jeu d'escarmouche expert sans hasard, purement basé sur le positionnement et l'anticipation."],
  [192, "Yubibo", 1, 0, "Origames", "Kosuke Takahashi", "05.03", "2-8", "10 min", "Adresse dextérité. Faites tenir des bâtonnets en équilibre sur vos doigts en suivant les défis imposés."],
  [193, "Post office", 1, 0, "Origames", "Evgeny Petrov", "05.03", "2-4", "45 min", "Logistique et livraison. Gérez un bureau de poste, triez les colis et optimisez les tournées de livraison."],
  [194, "Ritual", 1, 0, "Palladis Games", "Tomás Tarragón", "05.08", "2-6", "25 min", "Coopération et déduction. Réalisez un rituel magique en échangeant des gemmes colorées sans parler."],
  [195, "Dadada", 1, 4, "Pixie Games", "Antoine Bauza", "09.09", "2-99", "30 min", "Ambiance sonore. Faites deviner des images en utilisant uniquement des sons et des onomatopées bizarres."],
  [196, "Ethernal Decks", 1, 1, "Pixie Games", "Hiroken", "09.09", "1-4", "40 min", "Jeu de plis expert. Les cartes jouées modifient les atouts et les règles pour les tours suivants."],
  [197, "Carnimal", 1, 0, "Pixie Games", "Bruno Cathala", "09.09", "2", "25 min", "Duel de majorité. Envoyez vos animaux sur différentes îles pour en prendre le contrôle au moment du décompte."],
  [198, "Cup the crab", 1, 0, "Pixie Games", "Michael Feldkötter", "09.09", "3-5", "20 min", "Rapidité et gobelets. Capturez les crabes de la bonne couleur avec votre gobelet avant vos adversaires."],
  [199, "Quorum", 1, 2, "Pixie Games", "R. Franco & F. Martinez", "09.09", "2-4", "45 min", "Politique et corruption. Influencez le sénat romain, votez des lois et poignardez (métaphoriquement) vos rivaux."],
  [200, "Préjugés", 1, 4, "Pixie Games", "Auteur Inconnu", "09.09", "2-6", "20 min", "Party game adulte. Jugez vos amis sur des questions absurdes ou osées. Rires (et disputes) garantis."],
  [201, "Fief England", 1, 2, "Pixie Games", "Philippe Mouchebeuf", "09.09", "2-4", "120 min", "Conquête et diplomatie. La version 'légère' de Fief : mariages, guerres et titres de noblesse en Angleterre."],
  [202, "Isla Bomba", 1, 1, "Play punk", "P. Mori & R. Conzadori", "09.01", "2-5", "30 min", "Extension Captain Flip. De nouveaux plateaux et tuiles pour encore plus de combos pirates et de prises de risque."],
  [203, "Brillant", 1, 0, "Ravensburger", "Ralf zur Linde", "17.01", "1-6", "25 min", "Roll & Write. Cochez des pierres précieuses sur votre grille pour optimiser le score de lumière."],
  [204, "Propolis", 1, 1, "Ravensburger", "Johnson, Melvin & Stankewich", "17.01", "1-4", "30 min", "Placement d'ouvriers. Envoyez vos abeilles récolter du nectar et agrandir la ruche pour produire du miel."],
  [205, "Koï", 1, 1, "Ravensburger", "Battiato, Borzi & Chiacchiera", "17.01", "1-4", "45 min", "Placement zen. Disposez vos carpes koï dans l'étang pour créer des motifs harmonieux et marquer des points."],
  [206, "Labyrinthe chrono", 1, 0, "Ravensburger", "Max J. Kobbert", "17.01", "2-4", "20 min", "Classique revisité. Le Labyrinthe en temps réel ou limité : déplacez les murs pour atteindre vos trésors au plus vite."],
  [207, "Carnuta", 1, 0, "Repos prod", "Goh, Hwang & Kim", "09.01", "2-4", "25 min", "Tactique nature. Un jeu de cartes où les animaux de la forêt s'affrontent ou s'entraident selon la chaîne alimentaire."],
  [208, "Chateau rossignol", 1, 1, "Sand Castle", "B. Cathala & J. Fraile", "16.01", "2", "45 min", "Duel asymétrique. L'un construit des fortifications, l'autre tente de s'infiltrer. Tension et bluff permanents."],
  [209, "Emblèmes", 1, 0, "Savana", "A. Bonnard & R. Galonnier", "14.02", "3-5", "30 min", "Programmation secrète. Choisissez vos actions pour étendre votre influence, mais anticipez celles des autres."],
  [210, "Tag Team", 1, 1, "Scorpion masqué", "Christian Martinez", "14.06", "2", "10 min", "Deck-building de poche. Un jeu de combat style arcade où vous switchez entre deux héros pour enchaîner les combos."],
  [211, "Encyclopedie montres", 1, 3, "Scorpion masqué", "Bauza, Lebrat & Rivière", "14.06", "2-4", "30 min", "Mémoire coopérative. Observez les monstres et reconstituez leurs fiches descriptives avant qu'ils ne s'échappent."],
  [212, "Panorama", 1, 0, "Scorpion masqué", "J. Messaud & M. Leblond", "14.06", "2-4", "20 min", "Collection de cartes. Créez le plus beau panorama en assemblant des cartes paysages qui se connectent."],
  [213, "Gardlings", 1, 0, "Schmidt Spiele", "M. & K. Amundsen Østby", "19.06", "1-4", "45 min", "Placement de tuiles. Aménagez votre jardin avec l'aide de petites créatures magiques pour gagner des prix."],
  [214, "One round ?", 1, 4, "Schmidt Spiele", "Tobias Tesar", "19.06", "2-12", "15 min", "Party game de paris. Pariez sur le succès des autres joueurs dans des défis simples et rapides."],
  [215, "Kingdom crossing", 1, 2, "Sorry we are french", "Marco Canetta", "10.01", "1-4", "120 min", "Stratégie de mouvement. Développez votre royaume en optimisant les déplacements de vos sujets sur la carte."],
  [216, "Epic melee", 1, 0, "Sorry we are french", "Matthias Cramer", "10.01", "3-6", "20 min", "Bagarre générale. Un jeu de cartes rapide où tout le monde tape sur tout le monde pour être le dernier debout."],
  [217, "Leda", 1, 2, "Sorry we are french", "P. & R. Libralesso, Y. Sayada", "10.01", "2", "30 min", "Duel futuriste. Affrontement tactique dans un univers SF avec gestion de main et de positionnement."],
  [218, "Dewan", 1, 1, "Space cowboys", "J. Goupy & Y. Levet", "09.01", "2-4", "40 min", "Majorité et influence. Placez vos conseillers pour contrôler les différentes régions du sultanat."],
  [219, "Amanite", 1, 0, "Spiral Editions", "Thanos Vasof", "10.04", "2-4", "30 min", "Déduction et poison. Ramassez des champignons, mais attention aux vénéneux cachés par vos adversaires."],
  [220, "Space Lab", 1, 0, "Studio H", "J. Goupy & C. Lebrat", "24.06", "1-4", "20 min", "Logistique spatiale. Gérez votre laboratoire en orbite, assemblez des modules et validez des expériences."],
  [221, "Tulikko", 1, 0, "Studio H", "J. Soleil & N. Melet", "24.06", "2-4", "20 min", "Placement rapide. Posez vos tuiles fleurs pour couvrir le plateau et marquer des points de zone."],
  [222, "Bella vista", 1, 1, "Studio H", "A. Mainini & B. Cathala", "24.06", "2-4", "45 min", "Construction 3D. Bâtissez une villa méditerranéenne en optimisant la vue et l'agencement des pièces."],
  [223, "Amarok", 1, 4, "Subverti", "Charlène Chaps", "19.01", "3-6", "15 min", "Bluff et rôles cachés. Loups contre Villageois : mentez sur votre identité pour survivre."],
  [224, "Sanctuary", 0, 2, "Super meeple", "Krzysztof Zięba", "05.05", "1-5", "150 min", "Pose de tuiles expert. Construisez et gérez un sanctuaire animalier géant, en soignant les enclos et les visiteurs."],
  [225, "Kronologic Babylon", 1, 1, "Super meeple", "Yoann Levet", "05.05", "1-4", "30 min", "Déduction temporelle. Enquêtez dans Babylone en 1920. Le positionnement des suspects change avec le temps."],
  [226, "Mythologies", 1, 0, "Super meeple", "Max & Froh", "05.05", "2-4", "40 min", "Collection de sets. Réunissez les dieux et héros de différentes mythologies pour former le panthéon le plus puissant."],
  [227, "Ayar", 1, 2, "Super meeple", "Thomas Spitzer", "05.05", "1-4", "90 min", "Civilisation Inca. Gérez la population et les ressources (pommes de terre, maïs) pour étendre votre empire."],
  [228, "World order", 1, 2, "Super meeple", "Bagiartakis", "05.05", "2-4", "180 min", "Simulation géopolitique. Prenez la tête d'une superpuissance (USA, Chine, Russie, UE) et étendez votre influence mondiale."],
  [229, "Revenant", 1, 2, "Super meeple", "Allan Kirkeby", "05.05", "1-4", "120 min", "Worker placement. Gérez une station spatiale hantée ou abandonnée, survivez et accomplissez la mission."],
  [230, "Life of amazonia", 1, 2, "Super meeple", "Kasper Lapp", "05.05", "1-4", "120 min", "Bag building nature. Reconstituez la jungle amazonienne, placez des animaux et arbres pour restaurer l'écosystème."],
  [231, "Usual crapules", 1, 4, "Sylex", "F. Couderc & C. Lauras", "05.32", "3-5", "30 min", "Bluff et négociation. Partagez le butin d'un braquage, mais essayez de doubler vos complices sans vous faire exclure."],
  [232, "Galileo Galilei", 0, 2, "Sylex", "Tomáš Holek", "05.32", "1-4", "100 min", "Eurogame astronomique. Observez les astres avec votre télescope, publiez des thèses et évitez l'Inquisition."],
  [233, "Postcard", 1, 0, "Synapses games", "Eric Dubus", "06.01", "1-4", "45 min", "Voyage et collection. Visitez des lieux touristiques, achetez des souvenirs et envoyez des cartes postales."],
  [234, "Frosted blooms", 1, 0, "Synapses games", "B. Cathala & L. Maublanc", "06.01", "1-4", "40 min", "Tuiles et majorité. Faites éclore des fleurs dans le givre pour contrôler les zones du jardin."],
  [235, "Circadia", 1, 0, "Synapses games", "Hisashi Hayashi", "06.01", "2-5", "30 min", "Gestion du rythme. Alignez vos actions sur le cycle circadien pour maximiser vos points de bien-être."],
  [236, "Archipels", 1, 0, "Tiki", "A. Droit & Y. Gobert", "05.10", "2-4", "45 min", "Exploration maritime. Naviguez d'île en île, découvrez des ressources et établissez des comptoirs."],
  [237, "Pouss' ta poule", 1, 3, "The Flying Games", "B. Turpin & Y. Lidy", "13.04", "2-4", "20 min", "Course familiale. Avancez votre poule sur le chemin, mais gare aux obstacles et aux renards !"],
  [238, "Heroes conquer", 1, 1, "Tribuo", "Tribuo Team", "13.01", "2-4", "60 min", "Flip & Write de conquête. Retournez des cartes pour lever des armées et cocher des territoires sur votre feuille."],
  [239, "Du bout des doigts", 1, 4, "Tribuo", "Rémi Bernard", "13.01", "2-6", "30 min", "Jeu sensoriel. Reconnaissez des textures ou des formes uniquement au toucher, les yeux bandés ou cachés."],
  [240, "Pyramire", 1, 1, "Tribuo", "Ughi & Rondelli", "13.01", "2-4", "60 min", "Stratégie égyptienne. Participez à la construction des pyramides en gérant vos ouvriers et les crues du Nil."],
  [241, "Dungeon Exit", 1, 0, "Unfriendly Games", "D. Carmona & K. Nguyen", "18.06", "1-2", "20 min", "Labyrinthe puzzle. Trouvez la sortie du donjon en manipulant les tuiles couloir et en évitant les pièges."],
  [242, "Le chat & la tour", 1, 0, "Unfriendly Games", "M. Takizawa & Namiki", "18.06", "1-5", "30 min", "Dextérité et équilibre. Grimpez sur une tour instable avec votre chat sans tout faire écrouler."],
  [243, "Heroes love to lie", 1, 0, "Unfriendly Games", "D. Carmona & K. Nguyen", "18.06", "2-5", "30 min", "Bluff héroïque. Vantez vos exploits de héros, mais mentez sur vos capacités pour impressionner la galerie."],
  [244, "LetterUp", 1, 0, "Unfriendly Games", "D. Carmona & K. Nguyen", "18.06", "1-2", "30 min", "Jeu de mots tactique. Empilez des lettres pour former des mots et voler les points de l'adversaire (façon Scrabble 3D)."],
  [245, "Dudo Amigo", 1, 4, "Victoire Edition", "Silvano Sorrentino", "05.14", "3-8", "10 min", "Bluff de dés (Perudo). Secouez votre gobelet, regardez vos dés et pariez sur le total de la table. Mentez ou doutez !"],
  [246, "Team Quack", 1, 0, "Wilson games", "E. Morin & T. Saeys", "18.06", "3-6", "20 min", "Coopératif canard. Aidez la famille canard à traverser le parc en coordonnant vos mouvements sans vous gêner."],
  [247, "Polaroid game", 1, 0, "Wilson games", "G. Waxkirsh & J. Harrison", "18.06", "3-10", "15 min", "Mémoire visuelle. Observez une scène photo quelques secondes, puis répondez à des questions de détail."],
  [248, "Oh my socks", 1, 3, "Wilson games", "A. Bauza & T. Rivière", "18.06", "2-5", "15 min", "Jeu de paires. Retrouvez les chaussettes identiques dans le tas de linge sale le plus vite possible."],
  [249, "Elixirus", 1, 1, "Wilson games", "D. Chapin & N. Kordowska", "18.06", "2-5", "40 min", "Collection et combinaison. Récoltez des ingrédients rares pour concocter des élixirs magiques aux effets puissants."],
  [250, "Cat trick", 1, 0, "Wilson games", "Nagian", "18.06", "3-5", "15 min", "Jeu de plis félin. Gagnez des plis pour récupérer des chats, mais certains sont des filous qui valent des points négatifs."],
  [251, "100 limit", 1, 0, "Ykanoly Studio", "E. Brault & F. Maussin", "08.06", "2-8", "20 min", "Culture générale chiffrée. Estimez des réponses (dates, quantités) sans jamais dépasser la réponse exacte (façon Juste Prix)."],
  [252, "Once Upon a Line", 1, 2, "Lucky Duck", "William Aubert", "05.01", "1-4", "90 min", "Aventure narrative à gratter. Suivez une ligne d'histoire, grattez des zones pour découvrir des mots cachés et résoudre l'intrigue."],
  [253, "Behind Gold", 1, 4, "FIJ Official", "Cédric Millet", "Showroom", "2-5", "15 min", "Enquête exclusive FIJ. Un jeu de déduction rapide créé spécialement pour le festival. Trouvez le coupable parmi les suspects."],
  [261, "Earth: Abundance", 1, 1, "Lucky Duck", "Maxime Tardif", "05.01", "1-5", "60 min", "Extension Earth. Ajoute de nouvelles cartes, des interactions entre joueurs et des graines pour enrichir vos écosystèmes."]
];

// 3. LOGIQUE DE RECONSTITUTION (Ne pas toucher)
// Cette fonction mappe automatiquement vos descriptions (index 9) et génère les liens (MyLudo + BGG)
export const initialGames = rawGames.map(g => {
  // Extraction de l'ID BGG depuis l'URL (index 11)
  const bggUrl = g[11] || "";
  const match = bggUrl.match(/\/boardgame\/(\d+)/);
  const bggId = match ? match[1] : null;

  return {
    id: g[0],
    title: g[1],
    category: CAT[g[2]],
    type: TYPE[g[3]],
    publisher: g[4],
    author: g[5],
    stand: g[6],
    players: g[7],
    duration: g[8],
    description: g[9],
    myludoUrl: g[10],
    bggUrl: g[11],
    // Si l'image récupérée est null, on tente de construire le lien direct BGG
    imageUrl: g[12] || (bggId ? `https://cf.geekdo-images.com/boardgame/${bggId}_md.jpg` : null)
  };
});